### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by BarracudaPff** [apmath-web/loans#1]
- Add stable branch
  - Create `.travis.yml` file
  - Edit `.giignore` file
  - Add ktor
  - Create simple Info program from template
---
  - Add validation dependency

**Comment by malinink** [comment]
Кирилл, что за беспредел?
Во первых, в начале надо было создать все задачи. Во вторых. где ветка дев? в третьих, почеу не закопировали шаблон который я уже подготовил?
В четвертых почему самостоятельно приняли PR?

**Comment by BarracudaPff** [comment]
@malinink 

1. Я для этого и создал milestone, чтобы разбить планирование задач на этапы, соответственно, сначала просто создал проект.
2. Ветку dev я не создал по привычке, обычно работал с stable-master, но потом заметил и перестроил.
3.1. Я сначала сделал просто рабочий проект, template - подзадача из API и BL
3.2. Здесь прошу прощения, я подумал что задача слишком тривиальная


Могу вернуть PR и откатить проект если это критично.

**Comment by malinink** [comment]
@BarracudaPff я уже все откатил
