### ISSUE TITLE
Add ServiceManager

### ISSUE THREAD

**Issue by BarracudaPff** [apmath-web/loans#22]
Found great lightweight DI for Kotlin and Ktor - [Koin](https://github.com/InsertKoinIO/koin)
- Add [Koin](https://github.com/InsertKoinIO/koin) dependency
- Create `ServiceManager`
- Implement Koin into Ktor
- Add documentation

**Comment by malinink** [comment]
In my opinion it is a more pragmatic to add DI into template first, and then pass it into project, what do you think of that idea?

**Comment by BarracudaPff** [comment]
Moved to apmath-web/template-kotlin#9
